### ISSUE TITLE
document use of `add_overall`

### ISSUE THREAD

**Issue by anajens** [insightsengineering/rtables#183]
Some time ago we talked about deprecating `add_overall`:

>lets deprecate the `add_overall` function on `gabe_tabletree_work` and @anajens please start using `add_overall_level` for the release in 4 months.

_Originally posted by @waddella in https://github.com/Roche/rtables/issues/172#issuecomment-799577274_

However, I still think we need this function in some cases:

```r
library(dplyr)
library(rtables)

# This does not give us a "total" column:
basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All", first = FALSE)) %>%
  split_cols_by("ARMCD", split_fun = drop_split_levels) %>%
  add_colcounts() %>%
  analyze(vars = "SEX") %>%
  build_table(ex_adsl)

# This gives the correct overall column:
basic_table() %>%
  split_cols_by("ARM") %>%
  split_cols_by("ARMCD", split_fun = drop_split_levels) %>%
  add_overall_col("All Patients") %>%
  add_colcounts() %>%
  analyze(vars = "SEX") %>%
  build_table(ex_adsl)

```

**Comment by waddella** [comment]
as per discussion

 - [ ] add `add_overall` argument in to `basic_table`
 - [ ] deprecate the `add_overall_col` function

**Comment by waddella** [comment]
revisiting this topic, `add_overall_col` is still useful to add a marginal column when there is nesting in column space. Hence, let's update the documentation when which method for adding an overall column should be used.

**Comment by Melkiades** [comment]
> Some time ago we talked about deprecating `add_overall`:
> 
> > lets deprecate the `add_overall` function on `gabe_tabletree_work` and @anajens please start using `add_overall_level` for the release in 4 months.
> 
> _Originally posted by @waddella in [#172 (comment)](https://github.com/insightsengineering/rtables/issues/172#issuecomment-799577274)_
> 
> However, I still think we need this function in some cases:
> 
> ```r
> library(dplyr)
> library(rtables)
> 
> # This does not give us a "total" column:
> basic_table() %>%
>   split_cols_by("ARM", split_fun = add_overall_level("All", first = FALSE)) %>%
>   split_cols_by("ARMCD", split_fun = drop_split_levels) %>%
>   add_colcounts() %>%
>   analyze(vars = "SEX") %>%
>   build_table(ex_adsl)
> 
> # This gives the correct overall column:
> basic_table() %>%
>   split_cols_by("ARM") %>%
>   split_cols_by("ARMCD", split_fun = drop_split_levels) %>%
>   add_overall_col("All Patients") %>%
>   add_colcounts() %>%
>   analyze(vars = "SEX") %>%
>   build_table(ex_adsl)
> ```

Checking the examples, it looks to me that output is as expected. The first one adds a split level to the first split, which is then divided by the second split. The second example instead adds one single Total column after the split happens. 

Added a note in `add_overall_levels()` in #905. Documentation for `add_overall_col()` is already reflecting the above discussion.

Closing this for now. Please feel free to reopen if necessary.
