### ISSUE TITLE
Is there a way to bold row labels for html tables?

### ISSUE THREAD

**Issue by anajens** [insightsengineering/rtables#206]
`Viewer` has the argument `row.names.bold` which does not seem to be in use right now. I'm wondering if there is an alternative simple way to add the markup?  For example, with `** My Label **`

```r
basic_table() %>%
  split_cols_by("ARM") %>%
  analyze("AGE", show_labels = "visible", var_labels = "** AGE **") %>%
  build_table(ex_adsl)
```

**Comment by m7pr** [comment]
yeah, in 2023 row.names.bold is still not used
https://github.com/insightsengineering/rtables/blob/e3945768476c0359a76ae7907c342ba6ca6718b9/R/Viewer.R#L45

**Comment by edelarua** [comment]
Closed by https://github.com/insightsengineering/rtables/pull/780 - use bold argument to as_html.
