### ISSUE TITLE
Add Vignette For Advanced Users

### ISSUE THREAD

**Issue by waddella** [insightsengineering/rtables#243]
including 
 - custom splitting functions
 - advanced use of `analyze` including `.spl_context` (debugging)

**Comment by edelarua** [comment]
This is covered for the most part by the [Controlling Splitting Behavior](https://insightsengineering.github.io/rtables/main/articles/split_functions.html), [rtables Advanced Usage](https://insightsengineering.github.io/rtables/main/articles/advanced_usage.html), and [Example Complex Analysis Function: Modelling Cox Regression](https://insightsengineering.github.io/rtables/main/articles/example_analysis_coxreg.html) vignettes.
