### ISSUE TITLE
Topic QC: final formatted rtable into computer readable format

### ISSUE THREAD

**Issue by imazubi** [insightsengineering/rtables#308]
Hi @gmbecker ,

I was wondering if there is a way to convert a final formatted rtable into a dataframe writeable in a computer readable format so that the QC can be easily done i.e by: 

-  using arsenal::comparedf() in r vs a sas table 
- or either by proc compare in SAS by a SAS programmer. 

There are some tables (i.e AE tables) with a considerable size that makes the visual QC difficult. With the current csv output would not be possible to QC programmatically. 

```
my_table <- basic_table() %>% 
  split_rows_by("Species") %>%
  analyze("Petal.Length") %>% 
  build_table(df = iris)

## export csv
export_as_tsv(my_table, "my_table.csv")
```

<img width="315" alt="image" src="https://user-images.githubusercontent.com/87760125/159174496-fe058418-f3f1-48f2-a76e-e4ce3dd8dfdb.png">
 
rtables is an incredible package and I believe the addition of this feature would be an amazing step forward to widely use the package in clinical trials.

**Comment by gmbecker** [comment]
Hi @imazubi,

So there are a few different things here. FIirst off, the output of that csv (actually the path_enriched_df, its not related to writing the file) is bugged.  My initial guess is that it has to do with the table only having one column, but I'm not sure yet. Regardless, that will get fixed.

At a higher level, we do have comparison facilities for actual rtables TableTree objects, which (optionally) take structure/pathing into account, so if the QCer is using R, I think that would probably be a better approach. See `?compare_rtables` for that functionality as it exists now.

Finally, Part of the roadmap for the work this year that @waddella and I have put together is pushing those comparison/QC funciontalities even further, so if that is a priority please let us know that.

**Comment by gmbecker** [comment]
Acute problem with csv export should be fixed (with regression test) int he above commit.

**Comment by imazubi** [comment]
Hi @waddella and @gmbecker, thanks for these comments. 
Happy that I helped unintentionally by solving the bug @gmbecker is commenting then :) 

We will get back to you with some SAS table soon.
@waddella however, as you say, I think it a huge quick win to be able to output formatted cells in `export_as_tsv`, and also adding the column counts when `export_as_tsv` (I see there is already an [issue](https://github.com/Roche/rtables/issues/290) created for this). 
In this way, SAS programmers would be even able to read this CSV and have access to the final formatted values to compare. 

Let's keep in touch.

**Comment by gmbecker** [comment]
There are issues with putting the counts in in a way that would be machine accessible, they would essentially have to be the first row of observations, which would muddy the waters a great deal in terms of format/meaning of the rest of them. 

The bottom line is that an rtable table is a much more information rich object than the tsv/csv format supports. I'm happy to see what we can do in this regard but it is important that understand the limitations of the target format here...

**Comment by imazubi** [comment]
Hi @gmbecker I see, and I totally agree that rtable table is a much more information rich object than the tsv/csv format supports. I was saying this as when QC-ing, the first thing folks check are the column counts. However, as said, I think to be able to output formatted cells in `export_as_tsv` would be a huge win.

**Comment by imazubi** [comment]
@gmbecker I will get back to you next week.

**Comment by imazubi** [comment]
Hi @gmbecker . 

- See here an iris formatted table created by using SAS and exported to a CSV. 
<img width="419" alt="image" src="https://user-images.githubusercontent.com/87760125/189933553-767b2c45-02b0-4065-8992-74cd9c093b0f.png">
- Look at the rtable exported to a csv file. 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/87760125/189934927-4438c5e6-07ff-4498-a907-0218e15502cd.png">

I feel that at least having the opportunity of obtaining a formated rtable in the computer readable format would be a good starting step to one day, be able to do some programmatic QC by using rtables.

**Comment by imazubi** [comment]
Hi @gmbecker, 

I realized that by using `matrix_form(tt, indent_rownames = TRUE)$strings`, then we can write the final formatted table in a computer readable format, so I feel we are good on this side as well. 

```
library(rtables)

adsl <- ex_adsl

my_table <- basic_table() %>%
  split_cols_by("SEX") %>%
  split_rows_by("RACE") %>%
  analyze("AGE")  %>%
  build_table(df = adsl)


my_tab2 <- rtables::matrix_form(my_table, indent_rownames = TRUE)$strings

my_tab_csv <- utils::write.table(
  x = my_tab2,
  file = "my_tab.csv",
  sep = ",",
  col.names = FALSE,
  row.names = TRUE,
  append = FALSE
)

```

<img width="460" alt="image" src="https://user-images.githubusercontent.com/87760125/200251908-55c5a768-d627-4e54-9978-e13806ec28b5.png">

**Comment by Melkiades** [comment]
@imazubi this is possible with `rtables::as_result_df` with `as_is = TRUE` option you will get the data.frame. This can be easily exported to excel
