### ISSUE TITLE
Usual indexing does not work for reordering columns in a table

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/rtables#338]
Hi @gmbecker and @waddella ,

I came across this little question today and it seems I am either missing something or `rtables` is missing something obvious.

Observation: The usual column indexing does not work for reordering columns in a table.

Example:
```r
x <- rtable(c("A", "B"), rrow("row 1", 1,2), rrow("row 2", 3, 4))
x
x[, c(2, 1)] # is the same as x
```

Workaround works though:
```r
cbind_rtables(x[, 2], x[, 1])
```

**Comment by gmbecker** [comment]
Hi @danielinteractive,

So because `rtables` supports column spanning, `tbl[, <out-of-order-indexes>]` is...less unambiguous than you would expect in the general case.  For Example, with the table:

```
> tbl <- rtable(header = c("A","A2", "B", "B2"), rrow("row", rcell(2, colspan = 2), rcell(5, colspan=2)))
> tbl
      A   A2   B   B2
—————————————————————
row     2        5   
```

What exactly should `tbl[, c(2,3)]` do?

**Comment by danielinteractive** [comment]
Thanks @gmbecker for looking at this,

I understand that column spans complicate the semantics here. My expectations would be like this:

```r
library(rtables)
tbl <- rtable(header = c("A","A2", "B", "B2"), rrow("row", rcell(2, colspan = 2), rcell(5, colspan=2)))
# A) Original table
tbl
# B) Subset
tbl[, c(1, 2)] # ok nice
# C) Another subset
tbl[, c(1, 2, 4)] # ok nice too
# D) Subset with changed order
tbl[, c(2, 1)] # why is this the same as B) ? No warning is given.
# Expected would be:
#
#      A2    A
# ————————————
# row     2

# Here the workaround is duplicating information but still correct from the contents:
cbind_rtables(tbl[, 2], tbl[, 1])

# E) Changed order across different colspans
tbl[, c(1, 3, 2, 4)] # why is this the same as A) ? No warning is given.
# Expected could be:
cbind_rtables(tbl[, 1], tbl[, 3], tbl[, 2], tbl[, 4])
```

**Comment by danielinteractive** [comment]
thanks @gmbecker for thinking further about this. I agree that in this case the naive workaround is not giving a satisfactory result. How about thinking about a coding path where in a second step the column headings are merged between subsequent columns? (could be also an optional feature that is by default on but could be switched off by the user if not wished) I think that could be more flexible / user friendly rather than forbidding any reordering that violates the hierarchical structure.

**Comment by gmbecker** [comment]
Closing as not-planned.
