### ISSUE TITLE
Add overall indent 

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/rtables#373]
- [x] modify `VTableTree` so it has a slot to carry it around
 - [x] getters and setter for the slot
 - [x] ensure it is preserved/transferred when subsetting a table
 - [x] Modify `MatrixPrintForm` (ie its constructor) so that it carries it around (in formatters)
 - [x] modify `MatrixPrintForm`'s `toString` method to indent everything _**including header/footer materials**_ (in formatters)
 - [x] modify `matrix_form` method for `VTableTree` to pass the value along

**Comment by Melkiades** [comment]
Shall I close this @gmbecker ?
