### ISSUE TITLE
as_latex() for rendering rtable objects

### ISSUE THREAD

**Issue by feigs** [insightsengineering/rtables#387]
Is it currently possible to render an rtable object to latex, as it is the case for html? (with as_html())? Is it something you are working on?

Thx

**Comment by Melkiades** [comment]
We are not working on it currently as it would need a lot of manual setting of flags for each row and a lot of manual spacing etc...

Nonetheless, there are nice tools online that convert html tables into latex ones (e.g. https://tableconvert.com/html-to-latex). I have tested that and it works well. For a more automatic way, there may be some package giving you this option, e.g. https://search.r-project.org/CRAN/refmans/rrtable/html/HTMLcode2latex.html or {huxtable}
