### ISSUE TITLE
Should we test pdfs for printed content?

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#415]
As far as I could see, there is no current method to test the effective formatting of the output pdf. I think PR #413 might have the draft for doing this, by means of the soft dependency on `pdftools`

**Comment by gmbecker** [comment]
Its a good idea to research this. There are ways of extracting text from pdf files. How far this would get us in our case, and whether it adds value remains to be seen but its certainly possible it would.

**Comment by gmbecker** [comment]
Closing this for now, we can reopen if we ever decide to pursue it
