### ISSUE TITLE
New feature - Column labels are not automatically wrapped

### ISSUE THREAD

**Issue by crazycatandy** [insightsengineering/rtables#422]
Hi Gabe, I think this feature will come in future as you mentions?
https://github.com/insightsengineering/citril/issues/109

**Comment by gmbecker** [comment]
Column label, row label, and cell wrapping are planned as future features, yes.

**Comment by crazycatandy** [comment]
I'm wondering if you can kindly give us an example about how it works in rtables now.

**Comment by shajoezhu** [comment]
Hi @crazycatandy and @gmbecker , I saw this on the kendis board that this is planned during the PI planning. Just want to double check our current status on this issue. Thanks! @Melkiades fyi

<img width="250" alt="image" src="https://user-images.githubusercontent.com/3692541/201887441-4fa72bea-78e6-43de-bc58-43d7eaec2986.png">

**Comment by Melkiades** [comment]
The feature is in place thanks to @gmbecker and we are refining it with a few fixes and test/coverage (see #450 and #449)

**Comment by crazycatandy** [comment]
> The feature is in place thanks to @gmbecker and we are refining it with a few fixes and test/coverage (see #450 and #449)

Hi Davide, can you please create an example of how it works in ```rtables``` now?

**Comment by Melkiades** [comment]
This is directly taken from the tests, and please be aware that we are still fixing a few problems while refining/documenting the new feature. Also, remember that this uses the dev versions of  `rtables` AND `formatters`.
```r
library(rtables)
library(dplyr)

trimmed_data <- ex_adsl %>% 
    filter(SEX %in% c("M", "F")) %>% 
    filter(RACE %in% levels(RACE)[1:2]) 

levels(trimmed_data$ARM)[1] <- "Incredibly long column name to be wrapped"
levels(trimmed_data$ARM)[2] <- "This_should_be_somewhere_split"

basic_table(title = "Enough long title to be probably wider than expected",
            main_footer = "Also this seems quite wider than expected initially.") %>%
    split_cols_by("ARM") %>%
    split_rows_by("RACE", split_fun = drop_split_levels) %>%
    analyze(c("AGE", "EOSDY"), 
            na_str = "A very long content to_be_wrapped_and_splitted",
            inclNAs = TRUE) %>%
    build_table(trimmed_data)
    
# To see the wrapping in console:
clw <- c(5, 7, 6, 6) + 12 # column widths in characters: 1st column is rownames, the rest are the other cols
cat(toString(tbl, widths = clw))
# To export it as pdf:
export_as_pdf(tbl, "tbl.pdf", colwidths = clw)
```

**Comment by shajoezhu** [comment]
thanks a lot! @Melkiades and @gmbecker

**Comment by crazycatandy** [comment]
> This is directly taken from the tests, and please be aware that we are still fixing a few problems while refining/documenting the new feature. Also, remember that this uses the dev versions of `rtables` AND `formatters`.
> 
> ```r
> library(rtables)
> library(dplyr)
> 
> trimmed_data <- ex_adsl %>% 
>     filter(SEX %in% c("M", "F")) %>% 
>     filter(RACE %in% levels(RACE)[1:2]) 
> 
> levels(trimmed_data$ARM)[1] <- "Incredibly long column name to be wrapped"
> levels(trimmed_data$ARM)[2] <- "This_should_be_somewhere_split"
> 
> basic_table(title = "Enough long title to be probably wider than expected",
>             main_footer = "Also this seems quite wider than expected initially.") %>%
>     split_cols_by("ARM") %>%
>     split_rows_by("RACE", split_fun = drop_split_levels) %>%
>     analyze(c("AGE", "EOSDY"), 
>             na_str = "A very long content to_be_wrapped_and_splitted",
>             inclNAs = TRUE) %>%
>     build_table(trimmed_data)
>     
> # To see the wrapping in console:
> clw <- c(5, 7, 6, 6) + 12 # column widths in characters: 1st column is rownames, the rest are the other cols
> cat(toString(tbl, widths = clw))
> # To export it as pdf:
> export_as_pdf(tbl, "tbl.pdf", colwidths = clw)
> ```
> 
> Output: ![Screenshot 2022-11-16 123008](https://user-images.githubusercontent.com/11279768/202169185-f00382fb-94ab-4f4c-97e1-1ed01e6a8990.png)

Thanks a lot for this example. We will do some testing and let you know by end of next sprint
