### ISSUE TITLE
title dissapears when rbinding two rtables

### ISSUE THREAD

**Issue by imazubi** [insightsengineering/rtables#427]
```
library(rtables)

adsl <- ex_adsl

t1 <- basic_table(title = "my table") %>%
  split_cols_by("ARM") %>%
  analyze("AGE") %>%
  build_table(df = adsl)

t2 <- basic_table(title = "my table") %>%
  split_cols_by("ARM") %>%
  analyze("SEX") %>%
  build_table(df = adsl)


rbind(t1, t2)

```
There is no title. 

![image](https://user-images.githubusercontent.com/87760125/196965152-030e6f3f-877a-49df-a787-dd284bf04c8c.png)

The need for binding rtables is quite high when we have the typical AE summary table where we have to deal with different filtered analysis ADAE datasets to get the target analysis population for subjects with at least one TEAE, AESI, etc. The best approach is to create subtables and then rbind them. 

![image](https://user-images.githubusercontent.com/87760125/196965991-6a055a1b-d554-43dc-8c19-46ce1aa00580.png)

```
> packageVersion("rtables")
[1] ‘0.5.2’
```

**Comment by gmbecker** [comment]
Hi @imazubi,

So a few things.

Firstly, rbinding tables that are aggregating the same data is something of an anti-pattern and generally should be avoided when possible, rather than being the best way to do this within the rtables framework.

Remember that layouts can define multiple top-level subtables, so the way we would create something analogous to your desired table

```{r}
lyt <- basic_table() %>%
    split_cols_by("ARM") %>%
    analyze("AGE") %>%
    split_rows_by("EOSSTT", split_fun = keep_split_levels("COMPLETED"),
                  child_labels = "hidden") %>%
    analyze("AGE", function(x) in_rows("Mean (COMPLETED only)" = mean(x)),
            format = "xx.xx")
```

Which gives us

```
build_table(lyt, ex_adsl)
                        A: Drug X   B: Placebo   C: Combination
———————————————————————————————————————————————————————————————
Mean                      33.77       35.43          35.43     
Mean (COMPLETED only)     33.33       34.86          34.76     
```

**Comment by Melkiades** [comment]
In my opinion, adding the functionality of keeping one of the titles (which one?) may be more problematic than just doing `main_title(__) <- "title"` on the final table.

**Comment by gmbecker** [comment]
@Melkiades agreed, we can't keep the titles in the general case. If they disagree, the only principled thing is to drop them (both).

We _could_ special case the cases where the titles are either identical, or one of them is empty, though. I'm not fully sure if we should do that or not, but it merits discussion and would be sufficient for this use case.

**Comment by imazubi** [comment]
Totally agree @Melkiades . I was not aware of the `main_panel()` function that could be applied at the rtable object level. 

From my side, we can close the issue. 

Thanks @gmbecker as well.

**Comment by Melkiades** [comment]
@gmbecker I agree with you and I think it makes sense to keep the titles in those two cases. I will take a closer look at `rbind` to see if we can add the "automatic" merge smoothly
