### ISSUE TITLE
Remove the line followed by reference footnote

### ISSUE THREAD

**Issue by crazycatandy** [insightsengineering/rtables#429]
Can we remove the line followed by reference footnote according to Tim's feedback: "Ideally a line would not appear and would be appear as part of the same footnotes as main footer"

Ref: #420

**Comment by gmbecker** [comment]
Main footer and referential footnotes have radically different behavior under pagination so even without the divider referential footnotes will *not* be part of the main footer.  @barnett11 can you provide additional guidance on exactly what behavior you're asking for?

**Comment by barnett11** [comment]
Hi @gmbecker ,
Primarily no line should appear. Ideally the footnotes for main and referential should also appear without spacing if possible.
Kind regards,
Tim

**Comment by Melkiades** [comment]
Ok then the standard behavior should not produce any separator between blocks, right? I would follow up on considerations in https://github.com/Roche/rtables/issues/411 and remove all kinds of separators (empty lines or horizontal lines). If the user wants to create a space can use the soon-to-be-deprecated `\n` or the suggested empty string `main_title(x) <- c("title", "")`. For aesthetic purposes, we can reinstate the possibility of a horizontal separator by means of a character flag that is parsed and substituted. For example, a single character with the needed character: `main_title(x) <- c("title", "-")`. If ever a single character is needed on a new line, it is certainly possible to do some workaround (using `\n`), but I doubt it is a common case.

**Comment by crazycatandy** [comment]
> Ok then the standard behavior should not produce any separator between blocks, right? I would follow up on considerations in #411 and remove all kinds of separators (empty lines or horizontal lines). If the user wants to create a space can use the soon-to-be-deprecated `\n` or the suggested empty string `main_title(x) <- c("title", "")`. For aesthetic purposes, we can reinstate the possibility of a horizontal separator by means of a character flag that is parsed and substituted. For example, a single character with the needed character: `main_title(x) <- c("title", "-")`. If ever a single character is needed on a new line, it is certainly possible to do some workaround (using `\n`), but I doubt it is a common case.

Please kindly **only implement what Tim suggests**: 
1) 'Main and referential should also appear without spacing' -  Remove the spacing between main and referential
2) 'Primarily no line should appear' - Remove lines that comes with reference footnote.

Thanks

**Comment by clarkliming** [comment]
I think this is already resolved accoding to tests
