### ISSUE TITLE
Better documentation for `paginate_table`

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/rtables#448]
Improve documentation for `paginate_table` output vs. rendered table output.

See discussion below:

> Pagination does not control rendering, it only identifies pagination breaks. Furthermore, table objects do not carry around their word-wrapping information, that occurs only at rendering time, so this is unintuitive, but expected behavior.
> 
> 
> See `export_as_txt`, which does both:
> 
> ```
> > cat(export_as_txt(tt, cpp = 60, tf_wrap = TRUE, page_break = "\n---xxxx---\n\n", paginate = TRUE))
> this is a long long table title that should be wrapped to a
> new line
> sub
> -------
> titles
> 
> —————————————————————————————————————————————————————————
>                                              F     M    U
> —————————————————————————————————————————————————————————
> ASIAN                                       121   110   0
> BLACK OR AFRICAN AMERICAN                   43    36    0
> WHITE                                       23    23    0
> AMERICAN INDIAN OR ALASKA NATIVE             0     0    0
> MULTIPLE                                     0     0    0
> NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER    0     0    0
> OTHER                                        0     0    0
> UNKNOWN                                      0     0    0
> —————————————————————————————————————————————————————————
> 
> this is an extra long table main footer and should also be
> wrapped
> 
> prov footer
> 
> ---xxxx---
> 
> this is a long long table title that should be wrapped to a
> new line
> sub
> -------
> titles
> 
> ————————————————————————————————————————————————————————————
>                                             UNDIFFERENTIATED
> ————————————————————————————————————————————————————————————
> ASIAN                                              0        
> BLACK OR AFRICAN AMERICAN                          0        
> WHITE                                              0        
> AMERICAN INDIAN OR ALASKA NATIVE                   0        
> MULTIPLE                                           0        
> NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER          0        
> OTHER                                              0        
> UNKNOWN                                            0        
> ————————————————————————————————————————————————————————————
> 
> this is an extra long table main footer and should also be
> wrapped
> 
> prov footer
> > 
> ```
> 
> 
> This should be more prominently documented than it is, please file a new issue to figure out where that should go and then do so.
> 
> _Originally posted by @gmbecker in https://github.com/Roche/rtables/issues/447#issuecomment-1310858580_
>

**Comment by gmbecker** [comment]
I believe the underlying issue here is superseded by the new pagination and exporter design in `formatters`, which givesthe option to paginate something in a way that does remember the widths you specified (though not on an rtables object), or explicitly ask for indices (in which case you're expected to handle that yourself).

Closing. If it comes up again we should open a new issue.
