### ISSUE TITLE
Adding search engine for website

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#482]
I would love to be able to search for strings in online documentation like it is possible in tern. Is it possible to add this functionality also here @cicdguy?

**Comment by gmbecker** [comment]
A larger question @cicdguy is if the search can be expanded to include formatters (and possibly rlistings) due to how things are split up.

**Comment by Melkiades** [comment]
but so why is this (https://roche.github.io/rtables/reference/custom_split_funs.html) is rendered like this (that is where I saw it)? 
![Screenshot 2022-12-08 171930](https://user-images.githubusercontent.com/11279768/206503303-b03c49db-f6dd-42be-84e8-ef2c566dab84.png)

**Comment by Melkiades** [comment]
> A larger question @cicdguy is if the search can be expanded to include formatters (and possibly rlistings) due to how things are split up.

This can be the subject of a new issue if it is a possible thing to do @cicdguy. In the meantime, I will close this issue as soon as the old links are removed

**Comment by pawelru** [comment]
@Melkiades  Isn't it done?

**Comment by gmbecker** [comment]
The issue is that for this to be fully useful, it would be nice if the search engine could cover both rtables and formatters, because as you saw, the divisions of code make sense technically but can be a bit confusing to the end user.

@cicdguy is that something that is possible?

**Comment by gmbecker** [comment]
@cicdguy any update on this? Is this (the combined rtables + formatters search index) still a live issue on your plate? Should this just be closed?

**Comment by gmbecker** [comment]
That is kind of what I figured. Does this issue belong here, or in the automation team's project board (or both)? @cicdguy

**Comment by Melkiades** [comment]
Closing this as there are no current plans to complete this. {rtables} remains the point of reference for all user-facing docs
