### ISSUE TITLE
Add examples to exporting functions

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/rtables#504]
I keep receiving more and more questions about output forms. Please add examples to the `export_as_tsv` and `export_as_rtf` presenting the structure of saved file so that we can refer those questions to docs which would contain everything users need. IMO it's relevant to showoff specific form of export to tsv. If it is the same as `path_enriched_df` - please explicitly refer to example in there.

**Comment by gmbecker** [comment]
I see a number of typos in the documentation for export_as_rtf, which we need to fix, but it does say

```
 This function creates a flat tabular file of cell values and
     corresponding paths via ‘path_enriched_df’. I then writes that
     data.frame out as a tsv file.
```

in the overall description. 

For `export_as_rtf` its not clear to me how to add rtf output to R documentation.

**Comment by pawelru** [comment]
Yes I have seen that too. This however does not necessarily mean that the output is identical to what `path_enriched_df` returns and there is no other function in between / afterwards (I checked the code - it's not but I don't want our users to dive into the codebase). I keep referring people to the output section in the Reference subpage, they will open export_as_rtf, scroll down to see examples and there is nothing. I think it would be good to add a minimal example in there even if there is not much difference to aforementioned fun.

> For export_as_rtf its not clear to me how to add rtf output to R documentation.

Simple as that:

```
x <- tempfile()
(simple table code) %>% export_as_rtf(file = x)
```

Plus optionally more complex example with optional argument usage.

**Comment by gmbecker** [comment]
This appears to be done.
