### ISSUE TITLE
Add "top_level_div" to allow section divs between top-level subtables

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/rtables#509]
e.g.

```
basic_table(top_level_div = "-") %>%
    split_cols_by("ARM") %>%
    split_rows_by("SEX", split_fun = drop_split_levels) %>%
    analyze("AGE") %>%
    split_rows_by("RACE", split_fun = drop_split_levels) %>%
    split_rows_by("SEX", split_fun = drop_split_levels) %>%
    analyze("AGE") %>%
    build_table(DM)
```

would result in 

```
                            A: Drug X   B: Placebo   C: Combination
———————————————————————————————————————————————————————————————————
F                                                                  
  Mean                        33.71       33.84          34.89     
M                                                                  
  Mean                        36.55       32.10          34.28     
-------------------------------------------------------------------
ASIAN                                                              
  F                                                                
    Mean                      33.55       34.00          34.90     
  M                                                                
    Mean                      35.03       31.10          34.39     
BLACK OR AFRICAN AMERICAN                                          
  F                                                                
    Mean                      33.17       30.58          33.85     
  M                                                                
    Mean                      37.40       32.83          34.14     
WHITE                                                              
  F                                                                
    Mean                      35.88       38.57          36.50     
  M                                                                
    Mean                      44.00       35.29          34.00

**Comment by shajoezhu** [comment]
Very nice feature!

**Comment by Melkiades** [comment]
I think for now, we can close this as it is possible to achieve with `section_div()` setter. Getting it done for the above-mentioned case can be complicated as you need to aim at a split that is not visible, and all the setters and getter are currently dependent on this. If desperately needed, we can come back to this, but it is already quite complex as is. 

For the future reader, this is possible by doing:

```r
library(rtables)
tbl <- basic_table() %>%
    split_cols_by("ARM") %>%
    split_rows_by("SEX", split_fun = drop_split_levels) %>%
    analyze("AGE") %>%
    split_rows_by("RACE", split_fun = drop_split_levels) %>%
    split_rows_by("SEX", split_fun = drop_split_levels) %>%
    analyze("AGE") %>%
    build_table(DM)
sec_div <- section_div(tbl)
sec_div[4] <- "-"
section_div(tbl) <- sec_div

tbl
```

**Comment by gmbecker** [comment]
I don't feel this is a good solution. It should be something that can simply be added in `basic_table` as that can be thought of as representing the root row split, so I don't really understand the complications in targeting it. 

Generally speaking, and with a few quite rare exceptions, post-processing of a `TableTree` object shouldn't be necessary to get core table behaviors out, imo. And having spaces between top-level subtables appears to be a core table behavior from what I am seeing "in the wild".

**Comment by Melkiades** [comment]
> I don't feel this is a good solution. It should be something that can simply be added in `basic_table` as that can be thought of as representing the root row split, so I don't really understand the complications in targeting it.
> 
> Generally speaking, and with a few quite rare exceptions, post-processing of a `TableTree` object shouldn't be necessary to get core table behaviors out, imo. And having spaces between top-level subtables appears to be a core table behavior from what I am seeing "in the wild".

It makes sense to limit this section div to the first level. I will prepare a PR by eod
