### ISSUE TITLE
create release tag at 3a369f33e9bb7d5672f53fe73f47cf94d8b94416

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#520]

**Comment by Melkiades** [comment]
I created a draft at the moment here https://github.com/Roche/rtables/releases/tag/untagged-990bad440177859acac5

I will add source code and the tag I think will be created automatically after release. Of course, this is under discussion as I do not know if 0.5.4 is right or if we should have 0.6.0 already. @cicdguy and @gmbecker please feel free to modify this accordingly. We need to have also formatters' release at the same time

**Comment by Melkiades** [comment]
PS: I also connected the announcement section to the release

**Comment by gmbecker** [comment]
@shajoezhu why is the release supposedly at that exact sha? we should discuss release plans

**Comment by shajoezhu** [comment]
Thanks @gmbecker .This is very open for discussion, let's chat tomorrow in our meeting. This is the commit after Davide's bug fix in formatters, and all downstream checks are fine, hence the tag.

**Comment by Melkiades** [comment]
We can close this now as the release will be managed by @gmbecker with different HEAD
