### ISSUE TITLE
adding vignette for "make custom split fun"

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#528]
please branch off and merge into 506_make_custom_split_fun, as we still testing downstream and making sure no downstream break changes. thanks!

**Comment by gmbecker** [comment]
@shajoezhu can you please let me know if someone is going to do this or if I need to do it in order to get it in for the release.

**Comment by shajoezhu** [comment]
I am adding this to the board. please focus on the training material in the meantime

**Comment by Melkiades** [comment]
This is done imo
