### ISSUE TITLE
Update example for make_split_fun , with list to include two functions

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#532]
can me make a second example please?

mysplitfun2, where the list include two functions?

_Originally posted by @shajoezhu in https://github.com/Roche/rtables/pull/526#discussion_r1102830794_

**Comment by Melkiades** [comment]
> It is very clear and well-documented in my opinion. Also, it is a nice addition with a well-contained doc page with separated function documentation and a good family structure (`#' @family make_custom_split`).
> I think it is important though to add a list of currently supported functions that can work with `make_split_fun` and not (via lists in the details section with the 3 options, pre, core, post) and seealso in other fun-doc pages. It is atm a bit self-standing. For example, it would be interesting to have better clarity on where I should use `trim_levels_in_group` and `trim_levels_in_facets`. The latter is missing an example; I know it is straightforward but I think it is needed with some disclaimers specifying why it is different from other trims.

_Originally posted by @Melkiades in https://github.com/Roche/rtables/pull/526#pullrequestreview-1293141302_

Just to keep track of this.

**Comment by gmbecker** [comment]
closed by #552
