### ISSUE TITLE
Release v 0.6.0 onto CRAN

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/rtables#558]
- [x] formatters 0.4.0 accepted on cran (insightsengineering/formatters#111)
- [x] increase versioned dependency on formatters to `>=0.4.0`
- [x] Bump version to 0.6.0
- [x] Submit to CRAN
- [x] Respond to CRAN feedback
- [x] Accepted on CRAN
- [x] merge cran_release_0.6.0 into main
- [x] tag github release 0.6.0

**Comment by gmbecker** [comment]
#559

**Comment by shajoezhu** [comment]
Thanks @gmbecker !

**Comment by gmbecker** [comment]
@cicdguy this can inform your efforts to formalize the release process on the CRAN side, fyi

**Comment by KlaudiaBB** [comment]
Looks good, thanks @gmbecker !
