### ISSUE TITLE
`obj_name,VNodeInfo-method {rtables}` documentation entry has also `make_row_df`

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#575]
This documentation entry has multiple accessor functions/generics and methods that could be documented stand-alone. Above all, the function `make_row_df` should, in my opinion, have a separate doc page. I found this by searching `rtables::prov_footer,VTitleFooter-method`, which is not the way to get this information (which is in `main_title {formatters}`). Also, it was not what I was looking for, i.e. the referential footnotes function `fnotes_at_path`, which is not linked there. I think footnotes should link to referential footnotes.

**Comment by gmbecker** [comment]
If you do `?make_row_df` you hit the help file for the generic (as you should) which lives in formatters and is descriptive of what the generic expects its methods to do.

Is there some reason the information there was insufficient for what you were trying to do?

**Comment by Melkiades** [comment]
This is closed for the same reasons as #574 by https://github.com/insightsengineering/rtables/issues/577
