### ISSUE TITLE
start using 'lifecycle' package

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#587]
@shajoezhu `rtables` doesn't currently use the `lifecycle` package, so you should open another issue if you want us to add that into the package as it will involve more than just this function.

_Originally posted by @edelarua in https://github.com/insightsengineering/rtables/issues/585#issuecomment-1472550303_

**Comment by gmbecker** [comment]
I don't think this is worth our limited bandwidth currently. We can reopen it later it it becomes a priority.
