### ISSUE TITLE
Update readme and include link for the 2nd advanced user training slides

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#597]

**Comment by Melkiades** [comment]
![Screenshot 2023-04-20 123304](https://user-images.githubusercontent.com/11279768/233340834-dc78a79c-b05f-4695-b4e1-beb23f764a42.png)
Can this be added? I lost the link at the moment

**Comment by shajoezhu** [comment]
this is a great idea! Hi @gmbecker , I was wondering if you could provide a copy of the slides? I think we could include it under "ext/"

**Comment by ayogasekaram** [comment]
waiting for slides to be available in a public repository.

**Comment by ayogasekaram** [comment]
Slides converted to pdf from [this git repo ](https://github.com/insightsengineering/adv_rtables_training). They've been uploaded to the NEST Onboarding folder. Note: this limits access to those within the Roche Org
