### ISSUE TITLE
`value_formats` is stand alone and needs more testing and a note in the vignette

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#598]
First: should this function be in `formatters`? I was looking for it because I remembered it but it needs to be easier to retrieve than ctrl+f on both reference web pages. The best is to connect it to the rest of the package via links (at least in the section it is in reference). I will open an issue now about that. A vignette description may also put it onto the "user-map".

Just as a reference on how I checked this information regarding `value_formats`:

It is stand-alone:
![Screenshot 2023-03-27 184827](https://user-images.githubusercontent.com/11279768/228016635-b5cdf106-41cd-45d4-8464-d8567d6ef344.png)

It has few and not specific tests:
![Screenshot 2023-03-27 184852](https://user-images.githubusercontent.com/11279768/228016736-66169040-aac1-44e3-899a-5b92febe311a.png)

It has no vignette mention:
![Screenshot 2023-03-27 184921](https://user-images.githubusercontent.com/11279768/228016809-cad3a6e6-0211-4bfc-a17b-8c79edee398c.png)

**Comment by gmbecker** [comment]
This one is...debatable. The core of the question is essentially if `rlistings` needs a `value_formats` method, but individual values are not allowed to have formats in `rlistings`, so I'd say the answer there is no. 

The other reason for something to be in `formatters` is if the internals of `formatters` itself need to call the generic (e.g., within the pagination or core toString machinery). This is not the case here. What few format-related needs there are in `formatters` are met by `obj_format` which **is** a generic within `formatters`.

So certainly its not _urgent_ that it be migrated; its not _incorrect_ that it lives in `rtables` from a technical standpoint. That said, I could see a reasonable argument for it being somewhat better placed there, as an extension of `obj_format`

Note that if it were to be put into `formatters`, the current `mf_formats` would probably need to be a method for it, but we'd need to figure out what that means about what interface it is imposing as a generic.
