### ISSUE TITLE
Wrong function mentioned in the RTable Excercise

### ISSUE THREAD

**Issue by deepak-bbk** [insightsengineering/rtables#603]
# Reporting an Issue with rtables training exercise

In the NEST rtables Workshop: versions 0.3.x, under the exercise there is a heading "Adding Row Structure Nesting: split_cols_by("handed")", there seems like typo as the heading part state adding row structure nesting but uses the split_cols_by("handed") function that seems to be split_rows_by ("handed"). though the example uses the right function.

* Adding **Row Structure** Nesting:**split_cols_by**("handed")

Copy
lyt <-basic_table() %>%
  split_cols_by("arm") %>%
  split_cols_by("gender") %>%
  add_colcounts() %>% 
  split_rows_by("country") %>%
  summarize_row_groups() %>%
  **split_rows_by**("handed") %>%
  analyze("age", afun = mean, format = "xx.x")

build_table(lyt, df)

Please refer to the below URL for the concern page-
https://pages.github.roche.com/NEST/training/202003_rtables.html

---
![rtable_row_structure](https://user-images.githubusercontent.com/130560207/231441004-930e5ec2-8c8d-4c93-8f68-93b86c8dbe42.jpg)

**Comment by npaszty** [comment]
@gmbecker @Melkiades 

@edelarua can you raise awareness of this issue and perhaps a SME team member can address.

**Comment by gmbecker** [comment]
To be honest, I don't even know where those training pages came from so I'm not the right person to ask here.

**Comment by shajoezhu** [comment]
I think this training material is seriously outdated, should be closed. @pawelru @cicdguy can we do that? we should be referring to new materials.

**Comment by gmbecker** [comment]
Closing this as addressed/out-of-scope for this repo.
