### ISSUE TITLE
More complete final example in `analyze` fun doc

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#604]
I think there are a lot of variables that are not showcased. We may want to add an example that shows how they work.

**Comment by gmbecker** [comment]
We could extend the examples a little bit, but in terms of completeness I think a link/reference to the relevant vignette is probably better. I don't know that we want to have (e.g.,) 5 really complicated analysis functions in the examples section. They will be difficult for readers to understand without prose explaining them, I think.

**Comment by gmbecker** [comment]
Going to close this as wontfix, I think theres too much going on for examples to cover every aspect.
