### ISSUE TITLE
version bump downstream package versions

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#633]
Blocked by 

- [x] https://github.com/insightsengineering/rtables/issues/607

see https://github.com/insightsengineering/rtables/blob/main/staged_dependencies.yaml for reference

 

- [x]  insightsengineering/tern:
- [ ]   insightsengineering/tern.mmrm:
- [ ]   insightsengineering/tern.rbmi:
- [ ]   insightsengineering/teal.widgets:
- [ ]   insightsengineering/teal.modules.clinical:
- [ ]   insightsengineering/teal.modules.general:
- [ ]   insightsengineering/teal.modules.hermes:
- [x]   insightsengineering/chevron:
- [x]   insightsengineering/citril:
- [ ]   insightsengineering/teal.reporter:
- [ ]   insightsengineering/tern.gee:
- [ ]   insightsengineering/scda.test:

**Comment by gmbecker** [comment]
@shajoezhu can this be closed? if so please close it. Thanks

**Comment by gmbecker** [comment]
@shajoezhu ping. Can this be closed?

cc @edelarua @Melkiades @ayogasekaram

**Comment by shajoezhu** [comment]
Hi @gmbecker , thanks for the tag. I will look into this during the PI.

hi @donyunardi , @gogonzo and I was wondering if we need to vbump rtables version in teal family packages. Thanks!
