### ISSUE TITLE
Is LaTeX supported ?

### ISSUE THREAD

**Issue by jr1234567** [insightsengineering/rtables#655]
### What is your question?

It is suggested in the presentation page that LaTeX is supported  "multiple output formats (html, ascii, **latex**, pdf, xml)", but I can't find any clue in the vignettes pages how to export to LaTeX. 
Is there a way to export to LaTeX, or is it not yet implemented ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gmbecker** [comment]
I have not heard back from the poster, so I am going to close this. @jr1234567 please feel free to respond here further or file a new issue if desired.
