### ISSUE TITLE
Fix R CMD CHECK note

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/rtables#682]
```
* checking for unstated dependencies in vignettes ... NOTE
'::' or ':::' imports not declared from:
  ‘broom’ ‘car’ ‘checkmate’
```

I believe that it's follow-up on https://github.com/insightsengineering/rtables/pull/617

**Comment by gmbecker** [comment]
@cicdguy this should have failed the PR checks, shouldn't it? Can you look into what happened there please?

@edelarua please revise the vignette and update the DESCRIPTION file with the new suggests

**Comment by pawelru** [comment]
> @cicdguy this should have failed the PR checks, shouldn't it? Can you look into what happened there please?

Requested extending notes blocklist here: https://github.com/insightsengineering/idr-tasks/issues/597#issuecomment-1631983080
