### ISSUE TITLE
[Bug]: tt_to_flextable title and subtitle switch places

### ISSUE THREAD

**Issue by icostatistics** [insightsengineering/rtables#688]
### What happened?

In the tt_to_flextable function, the title and subtitles have switched places in the flextable object, as seen when running the below example code from the function description. The subtitle is above the title, which is a bit strange...
```r
analysisfun <- function(x, ...) {
  in_rows(row1 = 5,
          row2 = c(1, 2),
          .row_footnotes = list(row1 = "row 1 - row footnote"),
          .cell_footnotes = list(row2 = "row 2 - cell footnote"))
}
lyt <- basic_table(title = "Title says Whaaaat", subtitles = "Oh, ok.",
                   main_footer = "ha HA! Footer!") %>%
  split_cols_by("ARM") %>%
  analyze("AGE", afun = analysisfun)
tbl <-  build_table(lyt, ex_adsl)
ft <- tt_to_flextable(tbl)
ft
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
Apologies @icostatistics for the late update, but I think this has been fixed already in September when I added `export_as_docx` and relative refactoring of flextable transformer ;)
