### ISSUE TITLE
[Bug]: test-pagination is failing on main

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/rtables#694]
### What happened?

A test is failing on main and it seems that it has not been detected.

I've tested this locally, on a docker image ~and locally with the latest `formatters@main`~ _(edit: works locally and on docker with latest `formatters@main`)_

### How to reproduce?

```bash
$ docker run -it --rm ghcr.io/insightsengineering/rstudio_4.3.1_bioc_3.17 /bin/bash
$ wget https://github.com/insightsengineering/rtables/archive/refs/heads/main.zip
$ unzip main.zip
$ R
```

```R
r> install.packages("rcmdcheck")
r> rcmdcheck::rcmdcheck("./rtables-main/")
```

### Relevant log output

```
── Failure (test-pagination.R:66:3): export_as_txt prints split level header correctly when using page_by ──
grepl("^\naaa: ALT", tbl_txt) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
```

Code snippet:

```R
r>   tbl <- basic_table() %>%
    split_rows_by("PARAMCD", labels_var = "PARAMCD", split_label = "aaa",
                  label_pos = "topleft",
                  split_fun = drop_split_levels, page_by = TRUE) %>%
    split_rows_by("AVISIT", label_pos = "topleft",
                  split_fun = keep_split_levels("SCREENING")) %>%
    analyze("AVAL") %>%
    build_table(ex_adlb[ex_adlb$PARAMCD == "ALT",])
tbl_txt <- tbl %>% export_as_txt(lpp = 100)

r> tbl
#aaa                  
#  AVISIT      all obs
#—————————————————————
#ALT                  
#  SCREENING          
#    Mean       50.30 

r> expect_true(grepl("^\naaa: ALT", tbl_txt))
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
to me it works:
```r
> tbl_txt <- tbl %>% export_as_txt(lpp = 100)
> tbl_txt
[1] "\naaa: ALT\n\n—————————————————————\naaa                  \n  AVISIT      all obs\n—————————————————————\nSCREENING            \n  Mean         50.30 \n"
```

**Comment by pawelru** [comment]
We have just discussed - it's likely due to the formatters version. In CI we are using main version whereas here most likely it's coming from CRAN. We do want to use main version but still min dependency needs to vbumped if this is true.

**Comment by averissimo** [comment]
Thanks @Melkiades I dug a bit more and my local version of `formatters@main` was not up-to-date

Installing that on the docker image passed the test _(as well as with a local refresh)_

Yup @pawelru , the `formatters` version needs to be vbumped as soon as it's released on CRAN

**Should I close the ticket or wait until there is an vbump on `formatters`?**

The problem with CRAN's version is reproducible with the chunks I've shared above and on the [verdepcheck "release" CI action](https://github.com/insightsengineering/rtables/actions/runs/5597734853/jobs/10236488216) _(that's currently being developed)_

![image](https://github.com/insightsengineering/rtables/assets/211358/ff6f923e-67e3-4e01-9f0c-277bc4876cfa)

**Comment by Melkiades** [comment]
I think you can close this for now. This is important though as it may be indicative of a general problem with non-cohort releases and I am starting to think that this is adding a lot of overhead work and limiting the space for new features. Just thinking out loud! We might mitigate this with verdepchek

**Comment by shajoezhu** [comment]
new release tag created, this should have been addressed. reopen if still problem
