### ISSUE TITLE
Vignette on qtable

### ISSUE THREAD

**Issue by anajens** [insightsengineering/rtables#695]
### Feature description

- How to use rtables for exploratory work
- Extension of `table()`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gmbecker** [comment]
See https://docs.google.com/presentation/d/1OIM_wPJ5tx-iu21-kW2fu6u6lWFqCau0bDgCHSlxOlg/edit?usp=sharing slides 13-23
