### ISSUE TITLE
[Feature Request]: Update introduction vignette

### ISSUE THREAD

**Issue by anajens** [insightsengineering/rtables#702]
### Feature description

Proposal outline:

### Introduction
The rtables R package provides a framework to create, tabulate and output tables in R. Most of the design requirements for rtables have their origin in studying tables that are commonly used to report analyses from clinical trials; however, we were careful to keep rtables a general purpose toolkit.
- reference paper

### Rtables conceptual model (new section)
- Table as a a faceted data visualization
- ggplot2 example graphic (titanic data?)
![Screen Shot 2023-08-02 at 4 29 00 PM](https://github.com/insightsengineering/rtables/assets/43623360/3dc425a4-7c59-4b3c-9d14-669ad47c1289)

### Rtables overview (New section)
- layout framework to formatted table
![Screen Shot 2023-08-02 at 4 31 05 PM](https://github.com/insightsengineering/rtables/assets/43623360/16e5b5ac-eba9-4fc2-b246-7cc10719067f)

The sections below should be mostly the same, unless we want to switch to using the titanic data to be consistent with graphic from paper

### rtables unique features vs other table packages.  (Moved section)
There are a number of other table frameworks available in R such as [gt](https://gt.rstudio.com/) from RStudio, [xtable](https://cran.r-project.org/package=xtable), [tableone](https://cran.r-project.org/package=tableone), and [tables](https://cran.r-project.org/package=tables) to name a few. There is a number of reasons to implement rtables (yet another tables R package):
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
for the comparison could be worth it to take a look here https://github.com/RConsortium/rtrs-wg
