### ISSUE TITLE
[Feature Request]: Move training slides into repo subdir

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/rtables#703]
### Feature description

Please create a new repo subdir `"demo"` / `"trainings"` / etc., add it to the buildignore and move ~all~ recent trainings in there. By doing this we will assure that those will remain accessible. Please also update links in the README file.
The background of this request is that recently we experienced that videos uploaded internally disappear due to retention policy update without any notification. In order to avoid situation like this we should start moving our training materials (of small size, i.e. excluding videos) into GH to assure that they remain accessible and all will be living in one place for future reuse.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by edelarua** [comment]
Currently rtables advanced training slides are stored as PDFs in the `inst/extdata` directory. Other slide decks linked in the README should be moved there as well.
