### ISSUE TITLE
[Feature Request]: Organise vignettes in sections

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/rtables#704]
### Feature description

As the number of articles grows - it would be more much easier for a beginner users to navigate if they will be organised in some sections. A great example can be found here: https://github.com/cynkra/dm/tree/main/demo that renders into the following https://dplyr.tidyverse.org/articles/index.html

I don't have any ideas about the sections and their descriptions. Please decide.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
I agree it is very relevant. I proposed to make it more modular a couple of times and once to make an ordered list on the README

> 3. Absolutely necessary is a sorted list of vignettes. I found major disorientation in going tentatively about which to do next.

_Originally posted by @Melkiades in https://github.com/insightsengineering/rtables/issues/360#issuecomment-1234512585_
