### ISSUE TITLE
The document is not correct in `formatters::main_footer` (it says main_footer is a character scalar, instead of a vector)

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#722]
> the document is not correct in `formatters::main_footer` (it says main_footer is a character scalar, instead of a vector)
> 
> #' @return a character scalar (`main_title`, `main_footer`), or #' vector of length zero or more (`subtitles`, `page_titles`, #' `prov_footer`) containing the relevant title/footer contents

Correct, this is a documentation bug that should be fixed @Melkiades @ayogasekaram

_Originally posted by @gmbecker in https://github.com/insightsengineering/rtables/issues/705#issuecomment-1690872400_

**Comment by ayogasekaram** [comment]
created issue in formatters repo: https://github.com/insightsengineering/formatters/issues/194
