### ISSUE TITLE
how to combine split_cols_by_multivar with split_cols_by freely?

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/rtables#729]
is it true that we can only have "split_cols_by_multivar" after other splits?

```r
library(rtables)
library(dplyr)
ANL <- DM %>% mutate(value = rnorm(n()), pctdiff = runif(n()))
## toy example where we take the mean of the first variable and the
## count of >.5 for the second.
colfuns <- list(function(x) rcell(mean(x), format = "xx.x"),
                function(x) rcell(sum(x > .5), format = "xx"))
basic_table() %>%
    split_cols_by_multivar(c("value", "pctdiff"),
                           varlabels = c("Measurement", "Pct Diff")) %>%
    split_cols_by("ARM") %>%
    split_rows_by("RACE", split_label = "ethnicity",
                  split_fun = drop_split_levels) %>%
    summarize_row_groups() %>%
    analyze_colvars(afun = mean, format = "xx.xx") %>%
    build_table(ANL)
```

it gives error like

```
Error: Error applying analysis function (var - NA): missing value where TRUE/FALSE needed
        occured at (row) path: RACE[ASIAN]
```

**Comment by shajoezhu** [comment]
Hey @clarkliming , unfortunately, at the moment `split_cols_by_multivar` needs to be called after `split_cols_by`

https://insightsengineering.github.io/tlg-catalog/tables/other/rmpt03.html

**Comment by Melkiades** [comment]
at the moment this is not possible, `split_cols_by_multivar` was designed to stay close to `analyze_colvars`. We need to sit down and redesign some of these use-cases as described here: https://github.com/insightsengineering/rtables/issues/690

**Comment by Melkiades** [comment]
Btw you can move row things up and then is exactly the same case I posted in #690, i.e. the core of the problem, no other col split after `split_cols_by_multivar`
