### ISSUE TITLE
[Bug]: table with line breaks in headers not displaying in Viewer pane

### ISSUE THREAD

**Issue by anajens** [insightsengineering/rtables#731]
### What happened?

Users may want to create tables with long column headers that they want to split using line breaks:
```
library(rtables)
library(dplyr)

colfuns <- list(function(x) rcell(mean(x), format = "xx.x"),
                function(x) rcell(sd(x), format = "xx.x"))

lyt <- basic_table() %>%
  split_cols_by_multivar(c("AGE", "AGE"), varlabels = c("Mean Age", "SD\nLine Break!!! \nAge")) %>%
  analyze_colvars(afun = colfuns)

tbl <- build_table(lyt, DM)
tbl
```

```
> tbl
                    SD      
              Line Break!!! 
   Mean Age        Age      
————————————————————————————
     34.2          6.9   
```

However trying to display the table in the RStudio Viewer pane creates an error:
```
> Viewer(tbl)
Error in apply(cells, 1, function(row) { : 
  dim(X) must have a positive length
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
I think we have like 5 issues related to this. It is time to acknowledge the need for this and do it @edelarua @ayogasekaram
