### ISSUE TITLE
follow-up to docx export

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#738]
Refinements need the following fixes:

- [x] refactor "auto" widths to have `layout = "fixed"` otherwise. See #766 
- [x] topleft vertical alignment and boldness
- [x] topleft could be merged with `flextable::merge_at` but then indentation could be inexact (and row counts need an exception)
- [x] translation of character width to mm or pt (fix width) - Lets rely on Word for wrapping and paginating (closed)
- [ ] #938
- [x] remove somehow `tbl` from theme; independent from `rtables` object (need some thinking for label_row boldness). Maybe can be null and assigned when in `tt_to_flextable` or error?
- [ ] low border in first page is missing if it spans multiple tables (could not find the option to change this behavior)
- [ ] Add a vignette about exports and update README with docx
- [x] merge file template and doc file usage
- [x] cast (...) from export to tt_to_flextable
- [x] add limits 6-12 for font_size
- [x] add selection of different pages (from export not from theme (or both?))
- [x] #924
- [x] #925
- [ ] #926
- [ ] #939

**Comment by clarkliming** [comment]
may I ask if we can allow the table to be exported into a existing file?

**Comment by Melkiades** [comment]
> may I ask if we can allow the table to be exported into a existing file?

You should be able with the template_file option. I did not test it fully though! Meaning that I do not know if the template format will be overloaded or vice-versa. It should just added with the specified style

**Comment by clarkliming** [comment]
I see. I was wondering if we should only use `file` as the only argument, like if `file` exists and is a docx file then append result to it; if `file` does not exist then start from new doc files.

**Comment by Melkiades** [comment]
> I see. I was wondering if we should only use `file` as the only argument, like if `file` exists and is a docx file then append result to it; if `file` does not exist then start from new doc files.

yes it makes sense if you think it is simpler I will add it to this issue
