### ISSUE TITLE
Allow suppression of column counts in select columns

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/rtables#752]
In some tables it would be helpful to hide/not to print column counts for specific columns, such as columns that perform operations on data from other columns where counts don't make sense (e.g. risk difference). Currently column count display is all or nothing and I'm not sure how difficult this would be to change.

See https://github.com/pharmaverse/falcon/issues/149 for an example of where this feature would be used.

**Comment by Melkiades** [comment]
This is quite complicated. For me, the API design is not obvious. Anyway, connected with https://github.com/insightsengineering/rtables/issues/135
