### ISSUE TITLE
[Question]: Desired output package and how to change column width after changing to flextable

### ISSUE THREAD

**Issue by pzhang-cims** [insightsengineering/rtables#766]
Hi, I would like to check if there is an expected package for rtables to docx,html,output? What comes to my mind is, using tt_to_flextable, then specify all the details on the flextable object and then print. While I'm customizing flextable details, I found that the column width cannot be specified. Would you please advise how I should proceed? Seems that there is an limitation of total width

```r
library(rtables)
DM <- pharmaversesdtm::dm
lyt <- basic_table() |>
  split_cols_by("ARM") |>
  split_rows_by("RACE",
    page_by = TRUE,
    page_prefix = "Sex",
    split_fun = drop_split_levels
  ) |>
  analyze("AGE", mean, format = "xx.xx")
tbl <- build_table(lyt, DM)



ft <- tbl %>%
  tt_to_flextable(max_width = "auto") %>%
  merge_v(part = "header") %>%
  flextable::width(j = 1:5, width = c(15, 2, 2, 2, 2))
ft
```

![image](https://github.com/insightsengineering/rtables/assets/138497887/c94890b6-c7be-461a-9e12-f53d337befd2)

As you can see, the column width of first column cannot be changed, no matter what value I assigned.

Thanks in advance for your help!

Best,

Peng

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
You can change this behavior by setting the layout properties as follows:
```

ft <- tbl %>%
  tt_to_flextable(max_width = "auto") %>%
  flextable::set_table_properties(layout = "fixed")
ft %>% 
  flextable::merge_v(part = "header") %>%
  flextable::width(j = 1:5, width = c(15, 2, 2, 2, 2)) 

```
