### ISSUE TITLE
[Question]: as_result_df or similar function about data structure.

### ISSUE THREAD

**Issue by pzhang-cims** [insightsengineering/rtables#773]
### What is your question?

Hi,

I have a question that for as_result_df that, if we can have an option to display all the values by row. For example the code below
```r
library(rtables)
DM <- pharmaversesdtm::dm
lyt <- basic_table() |>
  split_cols_by("ARM") |>
  split_rows_by("RACE",
    page_by = TRUE,
    page_prefix = "race",
    split_fun = drop_split_levels
  ) |>
  analyze("AGE", mean, format = "xx.xx")

tbl <- lyt %>% build_table(DM)

tbl %>% as_result_df()
```
![image](https://github.com/insightsengineering/rtables/assets/138497887/1a696714-7dfc-4ad1-bcd9-f7578c2a7950)

This will give us 4 rows and 4 columns for the mean. Instead, can we have 16 rows and 1 column only for the result? Or if we have any existed function to deal with such ARD function? 

Best,

Peng

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
You can flatten it out with {purrr} by taking only the interested columns:

```r
res_df <- tbl %>% as_result_df()

res_df[, names(tbl)] %>% purrr::flatten()

# better because works also for nested columns
res_df[, seq_len(ncol(tbl)) + ncol(res_df) - ncol(tbl)] %>% purrr::flatten()
```

**Comment by Melkiades** [comment]
Yes, it was the same but then got renamed because of a conflict with another project we are working on. For the time being, that is the point of reference

**Comment by pzhang-cims** [comment]
Many thanks for the explanation, Melkiades.
