### ISSUE TITLE
Is there a way to get a data frame of the final TableTree object?

### ISSUE THREAD

**Issue by mrmorgan17** [insightsengineering/rtables#784]
### What is your question?

If I have a TableTree object `tbl`, is there a way to make the main table what was created (what I see with `Viewer(tbl)`) into a data frame or a data.table? I know there is `as_result_df()` but this function returns the raw values and not the final calculated values. I know the columns will likely be characters, which is fine but are there other options besides `as_result_df()`?.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by shajoezhu** [comment]
hi @mrmorgan17 , can you be more specific with "the final calculated values". Do you mean the value that is actually printed in the table? that has been formatted?

**Comment by mrmorgan17** [comment]
@shajoezhu I think so. For example, I calculated these cell values using `analyze`:
```
tbl <- basic_table() |>
  split_cols_by("TRTGR", ref_group = "PLACEBO", split_fun = add_overall_level("Overall", first = FALSE)) |>
  split_rows_by("PARAM") |>
  split_rows_by("TIME_GROUP") |>
  split_rows_by("HLTHSTAT") |>
  analyze(vars = c("AVAL", "CHG"), afun = function(x) {
    in_rows(
      "N" = rcell(sum(!(is.na(x))), format = "xx"),
      "Mean (SD)" = rcell(c(mean(x, na.rm = TRUE), sd(x, na.rm = TRUE)), format = "xx.xx (xx.xx)"),
      "Median" = rcell(median(x, na.rm = TRUE), format = "xx.xx"),
      "(Q1, Q3)" = rcell(c(quantile(x, .25, na.rm = TRUE), quantile(x, .75, na.rm = TRUE)), format = "(xx.xx, xx.xx)"),
      "Min, Max" = rcell(c(range(x)), format = "xx.x, xx.x")
    )
  }) |>
  build_table(adlb)
```

And if I use `as_result_df(tbl)`, the "Mean (SD)" rows come out like so: `c(43.4259259259259, 1.99624035165591)`, the "(Q1, Q3)" values come out like: `c(`25%` = 42, `75%` = 45)`, and the "Min, Max" rows come out like: "c(-6, 5)".

Ideally I'd like these `DataRow`s to be formatted like they are when I use `Viewer(tbl)` and again I am just wondering if that is possible. Happy to provide more clarification as well.

**Comment by Melkiades** [comment]
I am already working on this. It is possible, I will add two options to as_result_df ;) stay tuned
