### ISSUE TITLE
[Bug]: pagination issue when export to PDF

### ISSUE THREAD

**Issue by lchensigma** [insightsengineering/rtables#788]
### What happened?

A bug happened!

```r
> export_as_pdf(result_cm, file="./table_cm.pdf", landscape = TRUE, colwidths = c(50, 15, 15, 15, 15))
Error in find_pag(pagdf, start, guess, rlpp = adjrlpp, min_siblings = min_siblings,  : 
  Unable to find any valid pagination between 1 and 5
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
Newer versions of `formatters` (>=5.4) give a more informative error. To get that anyhow, you can use the same inputs for `paginate_table` with `verbose = TRUE,` and you will see where and why your inputs are not enough to paginate the table

**Comment by shajoezhu** [comment]
hi @lchensigma , can we please follow up on this, if this is still an issue for you? Thanks!

**Comment by Melkiades** [comment]
There is also an utility function called `diagnose_pagination` that gives more information

**Comment by lchensigma** [comment]
@Melkiades, Thank you. Here is what I got. I get package can not automatically wrap the long line. 

```diagnose_pagination(result_cm)```

````
Show in New Window
Error in FUN(X[[i]], ...) : 
  Width of row labels equal to or larger than specified characters per page.
````

**Comment by Melkiades** [comment]
@lchensigma that error means that the number of characters per page (parameter `cpp`) is too low for the width of your row labels. We are trying to harmonize the parameters in a way that if you add colwidths, it is also taken into account for the cpp parameter, but you still need to change cpp to fix this. Can you set it to say cpp=200? (cpp does horizontal pagination which you do not need right?)

**Comment by lchensigma** [comment]
Thank you. I tried and still got the error.

```
export_as_pdf(result_cm, file="./table_cm.pdf", landscape = TRUE, colwidths = c(50,15,15,15,15), cpp=200)
```

```
Error in find_pag(pagdf = pagdf, start = start, guess = origuess, rlpp = rlpp,  : 
  Unable to find any valid pagination split between rows 1 and 5. 
Inserted cpp (column-space, content per page) : 17
Need-to-repeat-in-each-page space (key values): 0
Remaining space: 17
Current space needed (with padding): 2
```

**Comment by Melkiades** [comment]
it seems you need more lpp (line per page). What is your current limit for this? (try lpp = 250) Try also to install rtables and formatters again from github, I have extended the error message information

**Comment by lchensigma** [comment]
I am not sure the limit for `lpp`. I assume it is default for the langscape.
```
> export_as_pdf(result_cm, file="./table_cm.pdf", landscape = TRUE, cpp=200, lpp = 250)
Error in pag_indices_inner(mf_cinfo(mf), rlpp = rcpp, verbose = verbose,  : 
  Width of row labels equal to or larger than specified characters per page.
```

**Comment by Melkiades** [comment]
> I am not sure the limit for `lpp`. I assume it is default for the langscape.
> 
> ```
> > export_as_pdf(result_cm, file="./table_cm.pdf", landscape = TRUE, cpp=200, lpp = 250)
> Error in pag_indices_inner(mf_cinfo(mf), rlpp = rcpp, verbose = verbose,  : 
>   Width of row labels equal to or larger than specified characters per page.
> ```

do not forget the colwidths otherwise it is not wrapping the row labels and I think you have something like 200+ characters per row label ;)

**Comment by lchensigma** [comment]
Thank you all for help. @Melkiades, add column width fix all the issue.

```
export_as_pdf(result_cm, file="./table_cm.pdf", landscape = TRUE, cpp=200, lpp = 250, colwidths = c(50,15,15,15,15))
```


![image](https://github.com/insightsengineering/rtables/assets/114957208/f75969f4-e00d-4bdf-85b0-103a4ab80c8d)
