### ISSUE TITLE
vignette on how to put model results in a table

### ISSUE THREAD

**Issue by waddella** [insightsengineering/rtables#80]
see the working code in the slides with 2 examples:

 1. using broom
 2. create a results `data.frame`

Not too much text is needed.

**Comment by danielinteractive** [comment]
We have one now internally, maybe that can be extended and then reused.

**Comment by danielinteractive** [comment]
Maybe @gmbecker and @waddella can have a look at it.

**Comment by gmbecker** [comment]
@edelarua do we have this now, either here or in falcon? if so likely closable

**Comment by edelarua** [comment]
Closing as we have a vignette on modelling cox regression in `rtables`: https://insightsengineering.github.io/rtables/main/articles/example_analysis_coxreg.html
