### ISSUE TITLE
inconsistent handling of 'root' as first path element and extremely unhelpful error messages in sort_at_path

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/rtables#816]
tt_at_path (and thus everything it is based on) silently removes 'root' when present as the first element of a path _whether or not that is the actual name of the root TableTree_.

Currently, `sort_at_path` only removes a first path element which matches the name of `tt` (the object having part of it's structure sorted).

This is inconsistent behavior and should be fixed.

Furthermore, this is _**heavily**_ compounded by the fact that there is no useful error signaling from `sort_at_path` when the specified path doesn't exist; it complains about "argument 1 not being a vector", which is actively misleading since the first argument to sort_at_path cannot be a vector, it has to be a `TableTree`

```r
 lyt <- basic_table() %>%
    split_rows_by("SEX", split_fun = keep_split_levels("F")) %>%
    split_rows_by("STRATA1") %>%
    summarize_row_groups() %>%
    analyze("AGE", mean, format = "xx.x")

tbl <- build_table(lyt, ex_adsl)
tbl
```

gives 

```
> tbl
            all obs  
—————————————————————
F                    
  A        63 (15.8%)
    mean      32.4   
  B        73 (18.2%)
    mean      34.8   
  C        86 (21.5%)
    mean      34.4   
```

Then, we have a path that works in `tt_at_path` but not in `sort_at_path`:

```
> tt_at_path(tbl, c("root", "SEX", "F", "STRATA1"))
          all obs  
———————————————————
A        63 (15.8%)
  mean      32.4   
B        73 (18.2%)
  mean      34.8   
C        86 (21.5%)
  mean      34.4   

> sort_at_path(tbl, c("root", "SEX", "F", "STRATA1"), scorefun = cont_n_allcols)
Error in order(scores, na.last = (na.pos != "first"), decreasing = decreasing) : 
  argument 1 is not a vector
```

The associated PR addresses both of these issues so that we get:

```
> sort_at_path(tbl, c("root", "SEX", "F", "STRATA1"), scorefun = cont_n_allcols)
            all obs  
—————————————————————
F                    
  C        86 (21.5%)
    mean      34.4   
  B        73 (18.2%)
    mean      34.8   
  A        63 (15.8%)
    mean      32.4   


> sort_at_path(tbl, c("root", "WRONG", "F", "STRATA1"), cont_n_allcols)
Error in sort_at_path(tbl, c("root", "WRONG", "F", "STRATA1"), cont_n_allcols) : 
  Unable to find child(ren) 'WRONG'
	 occured at path: 
  Use 'make_row_df(obj, visible_only = TRUE)[, c("label", "path", "node_class")]' or
      'table_structure(obj)' to explore valid paths.

> sort_at_path(tbl, c("SEX", "*", "WRONG"), cont_n_allcols)
Error in sort_at_path(oldkids[[i]], path = curpath[-1], scorefun = scorefun,  : 
  Unable to find child(ren) 'WRONG'
	 occured at path: SEX -> * (F)
  Use 'make_row_df(obj, visible_only = TRUE)[, c("label", "path", "node_class")]' or
      'table_structure(obj)' to explore valid paths.
```

Note its mildly debatable how the "root" portion of an unmatched path is reported when the actual root object's name is not "root".

The above is more common than it used to be;   root was always there (when constructing with `build_table`), but a number of years ago now, I changed it based on feedback so that if the root would itself have only one child, that child is returned from `build_table` instead so there is no structure named 'root'. 

Here I include 'root' in the path recap in error messages only if it actually matched the name of the object (ie the root element); its not clear to me whether that will be more or less confusing to users than saying an error where we can't find a particular child occurred at a place in the structure which already didn't exist. I think reporting the actual path (minus the incorrect root element) is reasonable, but can see the argument for including it as well.

Realistically, supporting _*actually incorrect*_ 'root' elements in paths should probably be deprecated (and thus throw deprecation warnings) in both `tt_at_path` and `sort_at_path`, though specifying the (actual) name of the root element (whether or not it is "root") will remain optional in both cases. 

Whatever the case moving forward, I think its important to change the `sort_at_path` behavior to match `tt_at_path` (and thus all the pathing support that relies on it under the hood, which is most of it AFAIR), which is what this change does (plus the reasonable error messages).

**Comment by shajoezhu** [comment]
Hi @gmbecker , many thanks for working on this. very happy to see the progress on this. We will need to check downstream breaking changes. thanks
