### ISSUE TITLE
as_result_df(), set as_is =T as default

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#827]
or not?

**Comment by edelarua** [comment]
@shajoezhu did we ever make a decision as to whether this should be changed?

**Comment by shajoezhu** [comment]
hi @telepath37 and @khatril , any preference for this?

**Comment by Melkiades** [comment]
Behavior has changed. This can be explored further, but afaik, `made_ard = TRUE` is the current priority and not the use of `df_to_tt` (this was designed for that)
