### ISSUE TITLE
update code of conduct, llint issue. see formatters for more details

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#842]
https://github.com/insightsengineering/formatters/pull/268/commits/b58d2607bf5fe381a18fc9038f77458755cc4e8d

**Comment by martincadek** [comment]
Created associated PR https://github.com/insightsengineering/rtables/pull/860.

Accepting https://github.com/insightsengineering/rtables/pull/860 will close https://github.com/insightsengineering/rtables/issues/842
