### ISSUE TITLE
complete implementation of `lifecycle`

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/rtables#866]
https://insightsengineering.github.io/rtables/main/reference/rbind.html
![image](https://github.com/insightsengineering/rtables/assets/12943682/90f40a87-ac73-40da-a8da-4fc6b520ec52)

- [x] add badge files with `usethis::use_lifecycle()` - please review changes done by this function
  - [x] This will promote `lifecycle` to the Imports and that's ok as we will be using this (see points below). Please don't forget to add this to the `pre-commit.yaml` file as well to keep it in sync.
- [x] for deprecated arguments use `foo(bar = lifecycle::deprecated(), ...) {...}` as per docs: https://lifecycle.r-lib.org/articles/communicate.html#deprecating-an-argument-providing-a-new-default
  - [x] (as per linked docs) use the following condition to check if argument is provided: `if (lifecycle::is_present(arg)) {`. In particular: not `if (!is.null(arg))`.
- [x] use `lifecycle` consistently and replace existing `.Deprecated()` calls: https://github.com/search?q=repo%3Ainsightsengineering%2Frtables%20.Deprecated&type=code
- [x] (supplementary to the above) - add appropriate badges for functions (not only arguments)

**Comment by Melkiades** [comment]
> https://insightsengineering.github.io/rtables/main/reference/rbind.html ![image](https://private-user-images.githubusercontent.com/12943682/328863016-90f40a87-ac73-40da-a8da-4fc6b520ec52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODY0NzAsIm5iZiI6MTcxNTU4NjE3MCwicGF0aCI6Ii8xMjk0MzY4Mi8zMjg4NjMwMTYtOTBmNDBhODctYWM3My00MGRhLWE4ZGEtNGZjNmI1MjBlYzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA3NDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZWNlMTkwODEyMzE3NmE5ODYyNzkxOWZjZTBkMTViYzM4ZGMzNDYwMWY2YWI1ZTkyZGEwYWQ5N2I0Y2UxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HnSAjU3qetSzLDU4lDG3rvyBQvUU9WziKoLj3rjx30U)
> 
> * [x]  add badge files with `usethis::use_lifecycle()` - please review changes done by this function
>   
>   * [x]  This will promote `lifecycle` to the Imports and that's ok as we will be using this (see points below). Please don't forget to add this to the `pre-commit.yaml` file as well to keep it in sync.
> * [x]  for deprecated arguments use `foo(bar = lifecycle::deprecated(), ...) {...}` as per docs: https://lifecycle.r-lib.org/articles/communicate.html#deprecating-an-argument-providing-a-new-default
>   
>   * [x]  (as per linked docs) use the following condition to check if argument is provided: `if (lifecycle::is_present(arg)) {`. In particular: not `if (!is.null(arg))`.
> * [x]  use `lifecycle` consistently and replace existing `.Deprecated()` calls: https://github.com/search?q=repo%3Ainsightsengineering%2Frtables%20.Deprecated&type=code
> * [x]  (supplementary to the above) - add appropriate badges for functions (not only arguments)

I think this is a very good guide to integrating full support of lifecycle. 
The last one is a bit difficult for rtables bc I think there are tons of functions and I think we will forget some of those. Let me check how @edelarua made it happen ;)
