### ISSUE TITLE
Multiple indentation happen for AE tables in the grade columns when exporting to docx

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#903]
Issue provided by a user. Will add reproducible code soon

**Comment by shajoezhu** [comment]
A similar issue is reported downstream in autoslider as well regarding indentation

https://github.com/insightsengineering/sme-tasks/issues/721

**Comment by Melkiades** [comment]
related issue: https://github.com/davidgohel/flextable/issues/652
