### ISSUE TITLE
[Bug]: Misalignment between row label and cells

### ISSUE THREAD

**Issue by JeanLucMoron** [insightsengineering/rtables#909]
the export_to_docx functionality works overall very well, however, I have noticed a slight vertical misalignment between the row label and the cell.
Looking at the formating details in MS Word, it seems that while both have vertical alignment = top, there is an additional paragraph setting which differs between both elements: vertical spacing (1pt vs 5 pts).  
![image](https://github.com/user-attachments/assets/99d50360-9e40-4130-b159-ebc7c8f0f5d3)

I have observed this in several standard tables like AET10.

**Comment by shajoezhu** [comment]
hi @JeanLucMoron and @Melkiades , were they using different font? i am guessing it is in the first column, and the font is a bit off too?

**Comment by JeanLucMoron** [comment]
@shajoezhu , they are using the same font (arial ) and size (9)
attaching the word document so that you can see
[aet10 (2).docx](https://github.com/user-attachments/files/16531831/aet10.2.docx)
