### ISSUE TITLE
[bug] Empty cells use a different font, causing unexpected linespacing

### ISSUE THREAD

**Issue by JeanLucMoron** [insightsengineering/rtables#910]
When exporting to docx format, if cells are empty they use a different font , which leads to unexpected spacing between lines.
The font name and size should be the same across the entire table , including empty cells
![image](https://github.com/user-attachments/assets/35a23ab5-7e54-45d4-a158-8ba8b522d7f8)

I have observed it with the standard table DMT01

When modifying manually in word the font name and size to be the same in the empty cells, the result looks more consistent:
![image](https://github.com/user-attachments/assets/d927bc3f-d605-43fc-9d4c-474a416c8d70)

**Comment by Melkiades** [comment]
I have checked this issue and it is resolved when horizontal padding is added uniformally. It is 12 because 9 font + 3 spacing
