### ISSUE TITLE
CI green for https://github.com/pawelru/ie_status?tab=readme-ov-file

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#916]
todos

- [ ] nosuggests https://github.com/insightsengineering/rtables/actions/runs/10437584162/job/28903931146

**Comment by Melkiades** [comment]
@shajoezhu you added formatters here, is it intentional?

**Comment by shajoezhu** [comment]
> @shajoezhu you added formatters here, is it intentional?

no, that was a very very bad copy and paste :p
