### ISSUE TITLE
Does rtables support page numbering?

### ISSUE THREAD

**Issue by thomas-neitmann** [insightsengineering/rtables#930]
On multi-page tables I'd like to display "Page x of n" on each page. Is this feature implemented? I couldn't find anything in the documentation.

**Comment by Melkiades** [comment]
it is present when paginating/exporting:

```r
library(rtables)

export_as_txt(basic_matrix_form(mtcars), pg_height = 5, pg_width = 4, page_num = default_page_number())

```

**Comment by thomas-neitmann** [comment]
Great, thanks!

**Comment by shajoezhu** [comment]
brilliant! Thanks guys! Hi @thomas-neitmann , I was wondering can you post this one on StackOverflow with the tag nest-rtables? We would like to embrace the usage of StackOverflow in the future
