### ISSUE TITLE
we have two versions tab, merge the changelog into the top entry for versions

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#944]
![image](https://github.com/user-attachments/assets/aa599399-ea6d-4324-91d3-f02eb2455327)

**Comment by pawelru** [comment]
Two buttons is a bug definitely. Thanks for the report.

For merging, I would rather to keep it as is. For two reasons:
- Introduce complexity in the multi-version docs feature. 
This is a general functionality applied for multiple repos so we would have to special case `rtables` repo or open a new parameter in the logic. Both add some complexity and I would like to keep this small if possible. I'm pretty sure that it's all possible but I just don't want to add the complexity unless we are very very sure that it's needed.
- Move away from standards
For pkgdown websites of R packages, usually (if not almost always) there is a "Changelog" button at the top. There are people who are reading this and they will be confused if it will be moved. Especially in our context of non-frequent "upgrades" of R packages in the project. We are teaching users how to get there to assess the changes and decide about the upgrade. That could make it a little bit more difficult.
