### ISSUE TITLE
update as_result_df() to export statistics by each “splits” (stats in a list)

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#947]
By default, create a long format data frame that stores statistic from each summarized groups (splits) in its own row
Currently, rtables returns results in ‘cells’, which means things like “Min - Max”, “Mean (SD)” are returned in one cell. We need tern to always return a named list (or lists) for all the statistics, and then we could update as_result_df() to export statistics by each “splits”

see tern https://github.com/insightsengineering/tern/issues/1352

**Comment by Melkiades** [comment]
may be useful: https://github.com/insightsengineering/cards/issues/43#issue-1969527308
