### ISSUE TITLE
error creating flextable

### ISSUE THREAD

**Issue by pavelaegorov** [insightsengineering/rtables#955]
Error when converting a rtable to a flextable:

Error in seq_len(nrow(raw_header)) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(nrow(raw_header)) : first element used of 'length.out' argument 

```r
library(rtables)

ADSL <- ex_adsl # Example ADSL dataset
lyt <- basic_table() %>%
  split_cols_by("ARM") %>%
  analyze(vars = "AGE", afun = function(x) {
    in_rows(
      "Mean (sd)" = rcell(c(mean(x), sd(x)), format = "xx.xx (xx.xx)"),
      "Range" = rcell(range(x), format = "xx.xx - xx.xx")
    )
  })

tbl <- build_table(lyt, ADSL)
tt_to_flextable(tbl)

```

**Comment by shajoezhu** [comment]
dear @pavelaegorov , the example works fine with rtables 0.6.10, formatters 0.5.9 which are our latest cran releases. please check your package versions. thanks

![image](https://github.com/user-attachments/assets/16c5e460-ec37-48a3-a0fc-c0f193b0de3f)

**Comment by pavelaegorov** [comment]
Thank you! Indeed, this issue happens on mcbook only. It works good on my windows machine.
