### ISSUE TITLE
[Bug]: Unable to use tt_to_flextable in version 0.6.10.9012

### ISSUE THREAD

**Issue by fyang-cims** [insightsengineering/rtables#974]
Hi there,

As mentioned in the title, I am unable to use the tt_to_flextable function in version 0.6.10.9012. However, it works fine if I install version 0.6.10 from CRAN.

Could you please kindly let me know how I can resolve this issue?

Thanks!

<img width="200" alt="image" src="https://github.com/user-attachments/assets/e28322b1-00f6-4c08-b776-b5122c613f98" />

**Comment by shajoezhu** [comment]
hi @fyang-cims , we are making a split of the two packages, to rtables and rtables.officer https://github.com/insightsengineering/rtables.officer, the ppt and docx related functionalities will be supported there. thanks you
